services:
  etl.web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl-web
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=etlprojectdb;Username=postgres;Password=1234
    ports:
      - "8080:8080"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: etl-postgres
    environment:
      POSTGRES_DB: etlprojectdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - etl-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d etlprojectdb"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped

volumes:
  etl-postgres-data:
